name: Build MicroPython Firmware for Raspberry Pi Pico

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout RackStatus
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get previous build number
      id: getPreviousBuild
      run: | 
        PREVIOUS_TAG=$(git for-each-ref --sort=-version:refname --count 1 --format="%(refname:short)" "refs/tags/*")
        echo result=${PREVIOUS_TAG} >> $GITHUB_OUTPUT
    
    - name: Get current build number
      id: getCurrentBuild
      if: success()
      env:
        PREVIOUS_BUILD: ${{ steps.getPreviousBuild.outputs.result }}
      run: echo result=$((++PREVIOUS_BUILD)) >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          build-essential \
          cmake

    - name: Checkout MicroPython
      uses: actions/checkout@v4
      with:
        repository: micropython/micropython
        path: micropython

    - name: Build MicroPython Cross Compiler
      working-directory: micropython
      run: |
        make -C mpy-cross
    
    - name: Copy project files
      run: |
        rsync -av --exclude='micropython' --exclude='.git' ./ ./micropython/ports/rp2/modules

    - name: Build firmware for RPi Pico W
      working-directory: micropython/ports/rp2
      run: |
        make BOARD=RPI_PICO_W submodules
        make BOARD=RPI_PICO_W clean
        make BOARD=RPI_PICO_W

    - name: Upload firmware for RPi Pico W
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: RackStatus-PicoW.uf2
        path: micropython/ports/rp2/build-RPI_PICO_W/firmware.uf2
      
    - name: Build firmware for RPi Pico2 W
      working-directory: micropython/ports/rp2
      run: |
        make BOARD=RPI_PICO2_W submodules
        make BOARD=RPI_PICO2_W clean
        make BOARD=RPI_PICO2_W

    - name: Upload firmware for RPi Pico2 W
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: RackStatus-Pico2W.uf2
        path: micropython/ports/rp2/build-RPI_PICO2_W/firmware.uf2

    - name: Rename firmware files
      run: |
        mv micropython/ports/rp2/build-RPI_PICO_W/firmware.uf2 micropython/ports/rp2/build-RPI_PICO_W/RackStatus-PicoW.uf2
        mv micropython/ports/rp2/build-RPI_PICO2_W/firmware.uf2 micropython/ports/rp2/build-RPI_PICO2_W/RackStatus-Pico2W.uf2

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      if: ${{ success() && github.ref_name == 'master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        custom_tag: ${{ steps.getCurrentBuild.outputs.result }}
      
    - name: Generate release diff
      if: ${{ success() && github.ref_name == 'master' }}
      env:
        BEGIN_COMMIT: ${{ steps.getPreviousBuild.outputs.result }}
        END_COMMIT: ${{ steps.getCurrentBuild.outputs.result }}
      run: git fetch --tags --force && git log --pretty=format:"* %s (%h)" ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.md

    - name: Create release
      uses: ncipollo/release-action@v1
      if: ${{ success() && github.ref_name == 'master' }}
      with:
        artifacts: "micropython/ports/rp2/build-RPI_PICO_W/RackStatus-PicoW.uf2,micropython/ports/rp2/build-RPI_PICO2_W/RackStatus-Pico2W.uf2"
        allowUpdates: true
        bodyFile: "release_notes.md"
        draft: false
        prerelease: false
        name: Build ${{ steps.getCurrentBuild.outputs.result }} (${{ github.ref_name }})
        tag: ${{ steps.getCurrentBuild.outputs.result }}
        token: ${{ secrets.GITHUB_TOKEN }}